@echo off
echo Installing Capacitor CLI and Core...
call npm install @capacitor/core @capacitor/android 
call npm install @capacitor/cli --save-dev
echo Building project...
call npm run build
echo Initializing Capacitor...
call npx cap init AMBLERT com.vishvas.amblert --web-dir dist
echo Adding Android platform...
call npx cap add android
echo Done!
